version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    # Добавляем healthcheck для мониторинга состояния
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/getTimestamp"]
      interval: 30s
      timeout: 10s
      retries: 3